Fixed matplotlib error
Due to the release of matplotlib 3.7, and some API changes I couldn't
find in the changelog, the constructor of `FisherBaseFigure` was
error-out in the following way:

> AttributeError: module 'matplotlib.style.core' has no attribute
  'rc_params_from_file'

Apparently one has to use `matplotlib` instead of `matplotlib.pyplot`,
which fixes the error.